---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  production.json: |
    {
      "log": {
        "level": "{{ .Values.logLevel }}"
      },
      "tls": {
        "enabled": true,
        "secretName": {{ .Values.tlsSecretName | quote }}
      },
      "hookName": "{{ include "psa-restricted-patcher.fullname" . }}-hooks",
      "hookNamespace": {{ .Release.Namespace | quote }},
      "addSeccompProfile": {{ .Values.addSeccompProfile }},
      "seccompProfile": "{{ .Values.seccompProfile  }}",
      "namespaces": {{ .Values.namespaces | toJson }},
      "defaultGid": {{ .Values.defaultGid }},
      "defaultUid": {{ .Values.defaultUid }},
      "defaultFsGroup": {{ .Values.defaultFsGroup }},
      "passthrough": {{ .Values.passthroughPatterns | toJson }},
      "ignoredAnnotations": {{ .Values.ignoredAnnotations | toJson }},
      "targettedAnnotations": {{ .Values.targettedAnnotations | toJson }}
    }