apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "psa-restricted-patcher.fullname" . }}-hooks
webhooks:
- name:  {{ include "psa-restricted-patcher.fullname" . }}.{{ .Release.Namespace }}.svc
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: {{ .Values.timeoutSeconds | int }}
  failurePolicy: {{ .Values.failurePolicy | quote }}
  reinvocationPolicy: {{ .Values.reinvocationPolicy | quote }}
  namespaceSelector:
    {{- toYaml .Values.namespaceSelector | nindent 4 }}
  objectSelector:
    {{- toYaml .Values.objectSelector | nindent 4 }}
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    {{- if .Values.namespaceScoped }}
    scope: "Namespaced"
    {{- else }}
    scope: "*"
    {{- end }}
  clientConfig:
    {{- /* Allow setting this but, have periodic check tied to health checks in hook that can update this it's rotated */}}
    {{- if .Values.hookCaBundle }}
    caBundle: {{ .Values.hookCaBundle }}
    {{- end }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "psa-restricted-patcher.fullname" . }}
      path: /api/v1/admission
