apiVersion: v2
name: psa-restricted-patcher
description: Automatically patches pods on creation to conform to the pod security restricted profile
type: application
version: 0.10.1
appVersion: "0.4.1"
maintainers:
  - name: bryopsida