replicaCount: 1

image:
  repository: ghcr.io/bryopsida/psa-restricted-patcher
  pullPolicy: Always
  tag: main

tlsSecretName: "psa-restricted-patcher"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true  
  capabilities:
    drop:
      - ALL

logLevel: "info"

resources:
  requests:
    memory: "64Mi"
    cpu: "0.1"
  limits:
    memory: "128Mi"
    cpu: "0.2"


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

certmanager:
  # -- enable using cert manager to issue a TLS certificate, if this is not enabled you must manage your own TLS secret
  enabled: true
  # -- Use a self signed issuer managed by this helm release
  useSelfSignedIssuer: true
  # -- When not using the self packaged/managed option from useSelfSignedIssuer, specify the IssuerType
  issuerType: Issuer
  # -- When not using useSelfSignedIssuer, specify the issuer name
  issuerName: ~
